apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-serivce
  labels:
    app: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
      - name: greeting-service
        image: beyla-demo/greeting-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
