apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-service
  labels:
    app: planet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planet-service
  template:
    metadata:
      labels:
        app: planet-service
    spec:
      containers:
      - name: planet-service
        image: beyla-demo/planet-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: planet-service
spec:
  selector:
    app: planet-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
